services:
  opentelemetry-collector-contrib:
    image: "otel/opentelemetry-collector-contrib:latest"
    ports:
      - "4318:4318"
    volumes:
      - "./otel-collector-config.yaml:/etc/otel/config.yaml"
      - "./otel_dump:/etc/otel/otel_dump:rw"
    depends_on:
      - jaeger
    command: ["--config=/etc/otel/config.yaml"]
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
      - "4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
