receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
processors:
  batch:
    send_batch_size: 1
    send_batch_max_size: 1

exporters:
  file/no_rotation:
    path: /etc/otel/otel_dump/dump.log
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/no_rotation, otlp]

